import { sino, REF_INGER_2022, NOTA_INGER } from './_comun.js';

export default {
  id: 'gds15',
  nombre: 'Escala de Depresión Geriátrica (GDS-15)',
  corto: 'GDS-15',
  dominio: 'afectivo',
  tipo: 'tamizaje',
  aliases: ['Yesavage', 'depresion', 'GDS', 'animo', 'estado afectivo'],
  problemas: ['depresión', 'tristeza', 'ánimo bajo', 'apatía', 'duelo'],
  descripcion: 'Tamizaje de síntomas depresivos: 15 preguntas de sí o no, de 0 a 15 puntos.',
  objetivo: 'Detectar síntomas depresivos en personas mayores. No establece el diagnóstico de depresión.',
  poblacion: 'Personas mayores sanas, enfermas o con deterioro cognitivo leve a moderado, en comunidad, hospital y cuidados de larga estancia (guía del INGER, 2022).',
  aplicacion: [
    'Explica que harás preguntas sobre su estado de ánimo y que tome en cuenta solo cómo se ha sentido durante la última semana.',
    'Lee cada pregunta tal cual y registra la respuesta de sí o no.',
    'En 5 preguntas suma la respuesta «no»; la puntuación de cada opción se muestra a la derecha.',
  ],
  tiempo: '5 min',
  direccionClinica: 'menor_mejor',
  textoMejoria: 'reducción de síntomas depresivos',
  textoEmpeoramiento: 'aumento de síntomas depresivos',
  min: 0,
  max: 15,
  campos: [
    sino('satisfecho', '¿En general, está satisfecho(a) con su vida?', 'no'),
    sino('renuncia', '¿Ha abandonado muchas de sus tareas habituales y aficiones?', 'si'),
    sino('vacia', '¿Siente que su vida está vacía?', 'si'),
    sino('aburrido', '¿Se siente con frecuencia aburrido(a)?', 'si'),
    sino('humor', '¿Se encuentra de buen humor la mayor parte del tiempo?', 'no'),
    sino('temor', '¿Teme que algo malo pueda ocurrirle?', 'si'),
    sino('feliz', '¿Se siente feliz la mayor parte del tiempo?', 'no'),
    sino('desamparado', '¿Con frecuencia se siente desamparado(a), desprotegido(a)?', 'si'),
    sino('casa', '¿Prefiere usted quedarse en casa, más que salir y hacer cosas nuevas?', 'si'),
    sino('memoria', '¿Cree que tiene más problemas de memoria que la mayoría de la gente?', 'si'),
    sino('vivo', '¿En estos momentos, piensa que es estupendo estar vivo(a)?', 'no'),
    sino('inutil', '¿Actualmente se siente un(a) inútil?', 'si'),
    sino('energia', '¿Se siente lleno(a) de energía?', 'no'),
    sino('desesperada', '¿Se siente sin esperanza en este momento?', 'si'),
    sino('mejor', '¿Piensa que la mayoría de la gente está en mejor situación que usted?', 'si'),
  ],
  bandas: [
    {
      min: 0, max: 4, etiqueta: 'Sin síntomas depresivos significativos', nivel: 'bien',
      texto: 'Tamizaje negativo: sin síntomas depresivos significativos. No descarta depresión si hay sospecha clínica.',
      sugerencias: [],
    },
    {
      min: 5, max: 15, etiqueta: 'Síntomas depresivos: tamizaje positivo', nivel: 'moderado', hallazgo: true,
      texto: 'Presencia de síntomas depresivos. Un tamizaje positivo no establece el diagnóstico de depresión: requiere entrevista clínica.',
      sugerencias: [
        'Entrevista clínica para confirmar o descartar un trastorno depresivo (criterios DSM-5-TR); el tamizaje no establece el diagnóstico.',
        'Explorar ideación suicida.',
        'Buscar factores contribuyentes: dolor, enfermedad médica, fármacos, duelo, aislamiento o deterioro cognitivo.',
      ],
    },
  ],
  notas: [
    'Tamizaje, no diagnóstico. Punto de corte ≥5, el de la guía del INGER (2022) y la validación española (Martínez de la Iglesia, 2002).',
    'A mayor puntaje, mayor probabilidad de depresión. Algunos materiales gradúan la intensidad (5–8, 9–11, 12–15), pero esa graduación no forma parte de la validación y aquí no se usa.',
    'Pierde fiabilidad en deterioro cognitivo moderado o grave y en afasia; en esos casos considera la escala de Cornell.',
    NOTA_INGER,
  ],
  referencias: [
    { texto: 'Yesavage JA, Brink TL, Rose TL, et al. Development and validation of a geriatric depression screening scale: a preliminary report. J Psychiatr Res. 1982;17(1):37-49.', doi: '10.1016/0022-3956(82)90033-4' },
    { texto: 'Sheikh JI, Yesavage JA. Geriatric Depression Scale (GDS): recent evidence and development of a shorter version. Clin Gerontol. 1986;5(1-2):165-73.', doi: '10.1300/J018v05n01_09' },
    { texto: 'Martínez de la Iglesia J, et al. Versión española del cuestionario de Yesavage abreviado (GDS) para el despistaje de depresión en mayores de 65 años. Medifam. 2002;12(10):620-30.' },
    REF_INGER_2022,
  ],
};
